- name: Verify that openproject directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/openproject"
    - "{{ docker_appdata_directory }}/openproject"
    - "{{ docker_appdata_directory }}/openproject/assets"
    - "{{ docker_appdata_directory }}/openproject/db"

- name: Set openproject assets directory ownership for container
  ansible.builtin.file:
    path: "{{ docker_appdata_directory }}/openproject/assets"
    owner: "1000"
    group: "1000"
    state: directory
    recurse: yes

- name: Copy openproject compose.yml
  template:
    src: ./roles/containers/openproject/compose.yml
    dest: "{{ docker_compose_directory }}/openproject/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker compose up openproject container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_directory }}/openproject/"
